In [1]:
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists 
# This is a vector

vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists 
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T) # calculate the transpose of the matrice

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3  = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:
vec4 = np.linspace(0,5,10) # the first command is a inclusive starting point, the end command is also inclusive
print(vec4)
print('')
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
Text = "SALUTE to the Mother EARTH";
Text.title()




'Salute To The Mother Earth'

In [8]:
# We can +-*/ arrays together if they're the right size 

vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [9]:
# We can do matrix multiplication 
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [10]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [11]:
# we can find the unique values in an array 

vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [12]:
# We can also use numpy to generate samples of a random variable 
rand_mat = np.random.rand(5,5) # uniform random variable 
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable 
print('')
print(rand_mat2)

[[0.81663902 0.60065797 0.2611303  0.34505379 0.25580764]
 [0.07052764 0.86769679 0.08798464 0.48766798 0.10102595]
 [0.48519103 0.7586402  0.67818483 0.39551718 0.9050519 ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]

[[ 0.06247022  1.22644326 -0.17513376  0.82770377  0.20477831]
 [-0.27954212 -1.11814848  0.29579506  0.67241294  0.60132985]
 [ 0.20950414 -0.30456159 -0.72411521  0.10946669  0.50771325]
 [ 0.46606297 -0.08091565 -1.66972001 -1.12617806 -0.1324352 ]
 [ 1.23658132  1.15210602  1.10725296 -1.71194558 -0.14732322]
 [-1.44517247  0.79119228  1.08826316 -0.31953354 -0.72490112]
 [ 0.24173554 -1.34976591 -0.32623926 -0.13151843 -0.04417173]
 [ 1.00385624 -0.22623477  1.00506613  0.74332084  0.0649372 ]
 [ 0.64319602  0.37231181  0.1863908   0.87011798  0.6239256 ]
 [ 0.43058569  0.84675114 -2.54473812 -0.35587942 -1.5792315 ]]


In [13]:
# we can also use numpy for statistical tools on arrays 

print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5433996853161178
0.8674783323994173


In [14]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.03742700908021879
1.2365813175519185


In [15]:
vec = np.arange(10,20,3)
print(vec)

[10 13 16 19]


In [16]:
vec = np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [17]:
vec1 = np.arange(0,12)
vec2 = vec1.reshape(4,3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
help(identity matrix)

SyntaxError: invalid syntax (<ipython-input-18-7efcbf00f587>, line 1)

In [19]:
np.cos(np.pi)

-1.0

In [20]:
np.exp(4)

54.598150033144236

In [21]:
np.log(6)

1.791759469228055

In [22]:
np.sqrt(1.44)

1.2

In [23]:
arr = np.arange(4,20,5)
print(arr)

[ 4  9 14 19]


In [24]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.56954562  0.19068896 -1.54416066 -1.06775562 -1.24859499 -1.0321349
 -1.45342807  1.06250156  1.56904992 -1.05720018 -1.44516381  0.84183896
 -0.2916515   0.40233778  0.3959843   0.09186925  0.71685554 -1.79694585
  0.32157996]
-1.4534280664764396


In [25]:
# we can access multiple entries at once using: 
print(rand_vec[4:9])

[-1.24859499 -1.0321349  -1.45342807  1.06250156  1.56904992]


In [26]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.56954562 -1.06775562 -1.45342807 -1.05720018 -0.2916515 ]


In [27]:
# what about matrices 
print(rand_mat)
print('')
print(rand_mat[1][2])
print('')
print(rand_mat[1,2])

[[0.81663902 0.60065797 0.2611303  0.34505379 0.25580764]
 [0.07052764 0.86769679 0.08798464 0.48766798 0.10102595]
 [0.48519103 0.7586402  0.67818483 0.39551718 0.9050519 ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]

0.08798463771959253

0.08798463771959253


In [28]:
print(rand_mat[0:2,1:3])

[[0.60065797 0.2611303 ]
 [0.86769679 0.08798464]]


In [29]:
# lets change some values in an array! 
print(rand_vec)
# the 5 is exclusive, so the index location values only change for 3 & 4
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.56954562  0.19068896 -1.54416066 -1.06775562 -1.24859499 -1.0321349
 -1.45342807  1.06250156  1.56904992 -1.05720018 -1.44516381  0.84183896
 -0.2916515   0.40233778  0.3959843   0.09186925  0.71685554 -1.79694585
  0.32157996]

[-0.56954562  0.19068896 -1.54416066  4.          4.         -1.0321349
 -1.45342807  1.06250156  1.56904992 -1.05720018 -1.44516381  0.84183896
 -0.2916515   0.40233778  0.3959843   0.09186925  0.71685554 -1.79694585
  0.32157996]

[-0.56954562  0.19068896 -1.54416066  1.          2.         -1.0321349
 -1.45342807  1.06250156  1.56904992 -1.05720018 -1.44516381  0.84183896
 -0.2916515   0.40233778  0.3959843   0.09186925  0.71685554 -1.79694585
  0.32157996]


In [30]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.81663902 0.60065797 0.2611303  0.34505379 0.25580764]
 [0.07052764 0.86769679 0.08798464 0.48766798 0.10102595]
 [0.48519103 0.7586402  0.67818483 0.39551718 0.9050519 ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]

[[0.81663902 0.60065797 0.2611303  0.34505379 0.25580764]
 [0.07052764 0.86769679 0.08798464 0.         0.        ]
 [0.48519103 0.7586402  0.67818483 0.         0.        ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]


In [31]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
# [:] means every single value in sub_mat should be changed to 3
print(sub_mat)

[[0.81663902 0.60065797 0.2611303 ]
 [0.07052764 0.86769679 0.08798464]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [32]:
print(rand_mat)

[[3.         3.         3.         0.34505379 0.25580764]
 [3.         3.         3.         0.         0.        ]
 [0.48519103 0.7586402  0.67818483 0.         0.        ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]


In [33]:
# In list's and using numpy, when you assign a matrix to a new matrix and you modify the new matrix then the values in the 
# original matrix are modified. This is avoided by using the .copy command 

sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.34505379 0.25580764]
 [3.         3.         3.         0.         0.        ]
 [0.48519103 0.7586402  0.67818483 0.         0.        ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]


In [34]:
vec = np.arange(10,20)
vec2 = vec[np.arange(0,10,3)]
print(vec2)

[10 13 16 19]


In [35]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [38]:
# lets save some arrays on th disk for use later!

np.save('saved_file_name', rand_mat2)
# the file gets saved in your working directory 
    

In [39]:
# Save multiple arrays in a zip file 
#  (the string name for the file) --> rand_mat = rand_mat <-- (the name of the np array)
np.savez('zipped_file_name',rand_mat=rand_mat, rand_mat2=rand_mat2)

In [40]:
# now let's load it 
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.06247022  1.22644326 -0.17513376  0.82770377  0.20477831]
 [-0.27954212 -1.11814848  0.29579506  0.67241294  0.60132985]
 [ 0.20950414 -0.30456159 -0.72411521  0.10946669  0.50771325]
 [ 0.46606297 -0.08091565 -1.66972001 -1.12617806 -0.1324352 ]
 [ 1.23658132  1.15210602  1.10725296 -1.71194558 -0.14732322]
 [-1.44517247  0.79119228  1.08826316 -0.31953354 -0.72490112]
 [ 0.24173554 -1.34976591 -0.32623926 -0.13151843 -0.04417173]
 [ 1.00385624 -0.22623477  1.00506613  0.74332084  0.0649372 ]
 [ 0.64319602  0.37231181  0.1863908   0.87011798  0.6239256 ]
 [ 0.43058569  0.84675114 -2.54473812 -0.35587942 -1.5792315 ]]



In [43]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.34505379 0.25580764]
 [3.         3.         3.         0.         0.        ]
 [0.48519103 0.7586402  0.67818483 0.         0.        ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]

[[ 0.06247022  1.22644326 -0.17513376  0.82770377  0.20477831]
 [-0.27954212 -1.11814848  0.29579506  0.67241294  0.60132985]
 [ 0.20950414 -0.30456159 -0.72411521  0.10946669  0.50771325]
 [ 0.46606297 -0.08091565 -1.66972001 -1.12617806 -0.1324352 ]
 [ 1.23658132  1.15210602  1.10725296 -1.71194558 -0.14732322]
 [-1.44517247  0.79119228  1.08826316 -0.31953354 -0.72490112]
 [ 0.24173554 -1.34976591 -0.32623926 -0.13151843 -0.04417173]
 [ 1.00385624 -0.22623477  1.00506613  0.74332084  0.0649372 ]
 [ 0.64319602  0.37231181  0.1863908   0.87011798  0.6239256 ]
 [ 0.43058569  0.84675114 -2.54473812 -0.35587942 -1.5792315 ]]
[[3.         3.         3.         0.34505379 0.25580764]
 [3.         3.    

In [44]:
# we can also save/load as text files.. but only single variables 

np.savetxt('text_file_name',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name', delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.34505379 0.25580764]
 [3.         3.         3.         0.         0.        ]
 [0.48519103 0.7586402  0.67818483 0.         0.        ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]

[[3.         3.         3.         0.34505379 0.25580764]
 [3.         3.         3.         0.         0.        ]
 [0.48519103 0.7586402  0.67818483 0.         0.        ]
 [0.70706849 0.91190583 0.85314504 0.95787149 0.49173875]
 [0.03742701 0.86528231 0.55028204 0.53158117 0.56191316]]


In [45]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [48]:
vec = np.array([4,7,8,9,10,6,1])
vec1[vec1>6] =2
print(vec1)

[0 1 2 3 4 5 6 2 2 2 2 2]
